// Code generated by genregistry; DO NOT EDIT.

package version

const RegistryDigest = "6f21efb11d0998a3888ae2b49bf63a19b6befb407fd10cdbc615aa5042c2504a"

// CompatibilityVersions returns a detached copy of the frozen Mission 1 compatibility set.
func CompatibilityVersions() map[string]int {
	return map[string]int{
		"dependency_lock":           1,
		"error_envelope":            1,
		"idempotency":               1,
		"input_output_schema":       1,
		"machine_manifest":          1,
		"operation_catalog":         1,
		"operation_registry_source": 1,
		"provider_contract":         1,
		"release_manifest":          1,
		"result_envelope":           1,
	}
}
