// Code generated by genregistry; DO NOT EDIT.

package version

const RegistryDigest = "54c81597c9c758446c3b12c8678212711433b95f3e0346a7051272ca2d03702e"

// CompatibilityVersions returns a detached copy of the frozen Mission 1 compatibility set.
func CompatibilityVersions() map[string]int {
	return map[string]int{
		"dependency_lock":           1,
		"error_envelope":            1,
		"idempotency":               1,
		"input_output_schema":       1,
		"machine_manifest":          1,
		"operation_catalog":         1,
		"operation_registry_source": 1,
		"provider_contract":         1,
		"release_manifest":          1,
		"result_envelope":           1,
	}
}
