package registry

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/StealthEyeLLC/ehjint/internal/contracts"
)

// GeneratedManifest is the deterministic tracked artifact digest set.
type GeneratedManifest struct {
	Generated      string              `json:"_generated"`
	SchemaVersion  int                 `json:"schema_version"`
	RegistryDigest string              `json:"registry_digest"`
	Artifacts      []GeneratedArtifact `json:"artifacts"`
}

// GeneratedArtifact binds one repository-relative path to exact bytes.
type GeneratedArtifact struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// VerifyGeneratedArtifacts checks the generated manifest and every listed tracked artifact.
func VerifyGeneratedArtifacts(root, expectedRegistryDigest string) error {
	manifestPath := filepath.Join(root, "api", "generated-manifest.json")
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("read generated manifest: %w", err)
	}
	var manifest GeneratedManifest
	if err := contracts.DecodeStrict(data, &manifest); err != nil {
		return err
	}
	if manifest.Generated != "Code generated by genregistry; DO NOT EDIT." || manifest.SchemaVersion != 1 {
		return fmt.Errorf("invalid generated manifest header or version")
	}
	if manifest.RegistryDigest != expectedRegistryDigest {
		return fmt.Errorf("generated manifest registry digest mismatch")
	}
	if len(manifest.Artifacts) == 0 {
		return fmt.Errorf("generated manifest is empty")
	}
	previous := ""
	for _, artifact := range manifest.Artifacts {
		if artifact.Path <= previous {
			return fmt.Errorf("generated manifest paths are not strictly ordered")
		}
		previous = artifact.Path
		if filepath.IsAbs(artifact.Path) || strings.Contains(artifact.Path, "..") || strings.ContainsRune(artifact.Path, '\x00') {
			return fmt.Errorf("unsafe generated artifact path %q", artifact.Path)
		}
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(artifact.Path)))
		if err != nil {
			return fmt.Errorf("read generated artifact %q: %w", artifact.Path, err)
		}
		digest := sha256.Sum256(content)
		if hex.EncodeToString(digest[:]) != artifact.SHA256 {
			return fmt.Errorf("generated artifact %q digest mismatch", artifact.Path)
		}
	}
	return nil
}
