// Package generator renders every derived EHJINT Mission 1 surface from the
// canonical registry and compatibility inputs.
package generator

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/StealthEyeLLC/ehjint/internal/contracts"
	"github.com/StealthEyeLLC/ehjint/internal/registry"
)

const generatedHeader = "Code generated by genregistry; DO NOT EDIT."

// Inputs is the complete validated human-authored source set.
type Inputs struct {
	Registry          registry.Source
	RegistryDigest    string
	Compatibility     contracts.CompatibilityFile
	ProviderContracts contracts.ProviderContractsFile
	Dependencies      contracts.DependencyLock
	Toolchain         contracts.ToolchainLock
}

// Artifact is one deterministic repository-relative generated file.
type Artifact struct {
	Path    string
	Content []byte
}

// LoadInputs validates all canonical source files before any output is written.
func LoadInputs(root string) (Inputs, error) {
	registryData, err := read(root, "registry/operations.json")
	if err != nil {
		return Inputs{}, err
	}
	registrySource, registryDigest, err := registry.ParseSource(registryData)
	if err != nil {
		return Inputs{}, fmt.Errorf("validate operation registry: %w", err)
	}

	compatibilityData, err := read(root, "config/compatibility.json")
	if err != nil {
		return Inputs{}, err
	}
	compatibility, err := contracts.ParseCompatibility(compatibilityData)
	if err != nil {
		return Inputs{}, fmt.Errorf("validate compatibility contract: %w", err)
	}

	providerData, err := read(root, "config/provider-contracts.json")
	if err != nil {
		return Inputs{}, err
	}
	providerContracts, err := contracts.ParseProviderContracts(providerData)
	if err != nil {
		return Inputs{}, fmt.Errorf("validate provider contracts: %w", err)
	}

	dependencyData, err := read(root, "config/dependencies.lock.json")
	if err != nil {
		return Inputs{}, err
	}
	dependencies, err := contracts.ParseDependencyLock(dependencyData)
	if err != nil {
		return Inputs{}, fmt.Errorf("validate dependency lock: %w", err)
	}

	toolchainData, err := read(root, "config/toolchain.lock.json")
	if err != nil {
		return Inputs{}, err
	}
	toolchain, err := contracts.ParseToolchainLock(toolchainData)
	if err != nil {
		return Inputs{}, fmt.Errorf("validate toolchain lock: %w", err)
	}
	if err := contracts.VerifyToolchainDependencyAgreement(toolchain, dependencies); err != nil {
		return Inputs{}, err
	}

	return Inputs{
		Registry:          registrySource,
		RegistryDigest:    registryDigest,
		Compatibility:     compatibility,
		ProviderContracts: providerContracts,
		Dependencies:      dependencies,
		Toolchain:         toolchain,
	}, nil
}

// Render returns the complete generated file set in strict lexical order.
func Render(inputs Inputs) ([]Artifact, error) {
	artifacts := make(map[string][]byte)
	add := func(path string, content []byte, err error) error {
		if err != nil {
			return fmt.Errorf("render %s: %w", path, err)
		}
		if _, exists := artifacts[path]; exists {
			return fmt.Errorf("duplicate generated artifact path %q", path)
		}
		if filepath.IsAbs(path) || strings.Contains(path, "..") || filepath.ToSlash(path) != path {
			return fmt.Errorf("unsafe generated artifact path %q", path)
		}
		if !bytes.HasSuffix(content, []byte("\n")) || bytes.HasSuffix(content, []byte("\n\n")) {
			return fmt.Errorf("generated artifact %q must contain exactly one final newline", path)
		}
		if bytes.Contains(content, []byte("\r")) {
			return fmt.Errorf("generated artifact %q contains non-LF line endings", path)
		}
		artifacts[path] = content
		return nil
	}

	addRendered := func(path string, renderer func() ([]byte, error)) error {
		content, err := renderer()
		return add(path, content, err)
	}
	renderers := []struct {
		path   string
		render func() ([]byte, error)
	}{
		{"internal/foundation/zz_generated_data.go", func() ([]byte, error) { return renderFoundationGo(inputs) }},
		{"internal/registry/zz_generated_catalog.go", func() ([]byte, error) { return renderRegistryGo(inputs) }},
		{"internal/version/zz_generated_compatibility.go", func() ([]byte, error) { return renderVersionGo(inputs) }},
		{"api/operation-catalog.json", func() ([]byte, error) { return renderOperationCatalog(inputs) }},
		{"api/cli.json", func() ([]byte, error) { return renderCLI(inputs) }},
		{"api/mcp-tools.json", func() ([]byte, error) { return renderMCP(inputs) }},
		{"api/compatibility.json", func() ([]byte, error) { return renderCompatibility(inputs) }},
		{"api/provider-contracts.json", func() ([]byte, error) { return renderProviderContracts(inputs) }},
		{"api/registry.digest", func() ([]byte, error) { return renderRegistryDigest(inputs) }},
		{"docs/generated/operations.md", func() ([]byte, error) { return renderOperationsDoc(inputs) }},
		{"docs/generated/contracts.md", func() ([]byte, error) { return renderContractsDoc(inputs) }},
		{"tests/generated/parity.json", func() ([]byte, error) { return renderParity(inputs) }},
	}
	for _, item := range renderers {
		if err := addRendered(item.path, item.render); err != nil {
			return nil, err
		}
	}

	for _, operation := range inputs.Registry.Operations {
		operation := operation
		base := strings.ReplaceAll(operation.Name, ".", "-")
		inputPath := "api/schemas/operations/" + base + ".input.schema.json"
		outputPath := "api/schemas/operations/" + base + ".output.schema.json"
		if err := addRendered(inputPath, func() ([]byte, error) { return renderOperationSchema(operation, "input") }); err != nil {
			return nil, err
		}
		if err := addRendered(outputPath, func() ([]byte, error) { return renderOperationSchema(operation, "output") }); err != nil {
			return nil, err
		}
	}

	for path, schema := range contractSchemas(inputs) {
		if err := add(path, schema, nil); err != nil {
			return nil, err
		}
	}

	manifest, err := renderGeneratedManifest(inputs.RegistryDigest, artifacts)
	if err != nil {
		return nil, err
	}
	if err := add("api/generated-manifest.json", manifest, nil); err != nil {
		return nil, err
	}

	paths := make([]string, 0, len(artifacts))
	for path := range artifacts {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	result := make([]Artifact, 0, len(paths))
	for _, path := range paths {
		result = append(result, Artifact{Path: path, Content: artifacts[path]})
	}
	return result, nil
}

// Write atomically installs generated artifacts beneath outputRoot.
func Write(outputRoot string, artifacts []Artifact) error {
	for _, artifact := range artifacts {
		path, err := safeJoin(outputRoot, artifact.Path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create generated directory for %s: %w", artifact.Path, err)
		}
		temporary, err := os.CreateTemp(filepath.Dir(path), ".genregistry-*")
		if err != nil {
			return fmt.Errorf("create temporary generated file for %s: %w", artifact.Path, err)
		}
		temporaryName := temporary.Name()
		cleanup := func() { _ = os.Remove(temporaryName) }
		if err := temporary.Chmod(0o644); err != nil {
			_ = temporary.Close()
			cleanup()
			return fmt.Errorf("set generated file mode for %s: %w", artifact.Path, err)
		}
		if _, err := temporary.Write(artifact.Content); err != nil {
			_ = temporary.Close()
			cleanup()
			return fmt.Errorf("write generated file %s: %w", artifact.Path, err)
		}
		if err := temporary.Sync(); err != nil {
			_ = temporary.Close()
			cleanup()
			return fmt.Errorf("sync generated file %s: %w", artifact.Path, err)
		}
		if err := temporary.Close(); err != nil {
			cleanup()
			return fmt.Errorf("close generated file %s: %w", artifact.Path, err)
		}
		if err := os.Rename(temporaryName, path); err != nil {
			cleanup()
			return fmt.Errorf("replace generated file %s: %w", artifact.Path, err)
		}
	}
	return nil
}

// Check proves that tracked generated files are byte-for-byte current and that
// no unexpected generated file exists inside the owned generated directories.
func Check(outputRoot string, artifacts []Artifact) error {
	expected := make(map[string][]byte, len(artifacts))
	for _, artifact := range artifacts {
		expected[artifact.Path] = artifact.Content
		path, err := safeJoin(outputRoot, artifact.Path)
		if err != nil {
			return err
		}
		actual, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated artifact %s: %w", artifact.Path, err)
		}
		if !bytes.Equal(actual, artifact.Content) {
			return fmt.Errorf("generated artifact is stale: %s", artifact.Path)
		}
	}

	ownedRoots := []string{
		"api",
		"docs/generated",
		"tests/generated",
	}
	for _, ownedRoot := range ownedRoots {
		absolute, err := safeJoin(outputRoot, ownedRoot)
		if err != nil {
			return err
		}
		err = filepath.WalkDir(absolute, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			relative, err := filepath.Rel(outputRoot, path)
			if err != nil {
				return err
			}
			relative = filepath.ToSlash(relative)
			if _, ok := expected[relative]; !ok {
				return fmt.Errorf("unexpected file in generated output ownership: %s", relative)
			}
			return nil
		})
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}

func read(root, relative string) ([]byte, error) {
	path, err := safeJoin(root, relative)
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", relative, err)
	}
	return data, nil
}

func safeJoin(root, relative string) (string, error) {
	if filepath.IsAbs(relative) || strings.ContainsRune(relative, '\x00') {
		return "", fmt.Errorf("unsafe relative path %q", relative)
	}
	clean := filepath.Clean(filepath.FromSlash(relative))
	if clean == "." || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("unsafe relative path %q", relative)
	}
	return filepath.Join(root, clean), nil
}

func formattedGo(source []byte) ([]byte, error) {
	formatted, err := format.Source(source)
	if err != nil {
		return nil, err
	}
	return ensureFinalNewline(formatted), nil
}

func prettyJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return ensureFinalNewline(data), nil
}

func ensureFinalNewline(data []byte) []byte {
	return append(bytes.TrimRight(data, "\n"), '\n')
}

func digest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

func renderGeneratedManifest(registryDigest string, artifacts map[string][]byte) ([]byte, error) {
	type entry struct {
		Path   string `json:"path"`
		SHA256 string `json:"sha256"`
	}
	type manifest struct {
		Generated      string  `json:"_generated"`
		SchemaVersion  int     `json:"schema_version"`
		RegistryDigest string  `json:"registry_digest"`
		Artifacts      []entry `json:"artifacts"`
	}
	paths := make([]string, 0, len(artifacts))
	for path := range artifacts {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	entries := make([]entry, 0, len(paths))
	for _, path := range paths {
		entries = append(entries, entry{Path: path, SHA256: digest(artifacts[path])})
	}
	return prettyJSON(manifest{
		Generated:      generatedHeader,
		SchemaVersion:  1,
		RegistryDigest: registryDigest,
		Artifacts:      entries,
	})
}
