// Command genregistry renders and checks all registry-derived EHJINT artifacts.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/StealthEyeLLC/ehjint/internal/generator"
)

func main() {
	root := flag.String("root", ".", "repository root containing canonical inputs")
	outputRoot := flag.String("output-root", "", "output root; defaults to -root")
	check := flag.Bool("check", false, "verify exact generated bytes without modifying files")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected positional arguments")
	}
	canonicalRoot, err := filepath.Abs(*root)
	if err != nil {
		fatalf("resolve repository root: %v", err)
	}
	canonicalOutput := canonicalRoot
	if *outputRoot != "" {
		canonicalOutput, err = filepath.Abs(*outputRoot)
		if err != nil {
			fatalf("resolve output root: %v", err)
		}
	}
	inputs, err := generator.LoadInputs(canonicalRoot)
	if err != nil {
		fatalf("load canonical inputs: %v", err)
	}
	artifacts, err := generator.Render(inputs)
	if err != nil {
		fatalf("render generated artifacts: %v", err)
	}
	if *check {
		if err := generator.Check(canonicalOutput, artifacts); err != nil {
			fatalf("generated artifact check failed: %v", err)
		}
		fmt.Printf("generated artifacts current: count=%d registry_sha256=%s\n", len(artifacts), inputs.RegistryDigest)
		return
	}
	if err := generator.Write(canonicalOutput, artifacts); err != nil {
		fatalf("write generated artifacts: %v", err)
	}
	fmt.Printf("generated artifacts written: count=%d registry_sha256=%s\n", len(artifacts), inputs.RegistryDigest)
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "genregistry: "+format+"\n", arguments...)
	os.Exit(1)
}
